services:
  web:
    build: .
    ports:
      - "8501:5000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
